
positions = {'Pitcher':"P",
          'Outfielder':"OF", 
       'Centerfielder':"CF", 
         'Leftfielder':"LF", 
        'Rightfielder':"RF",
           'Infielder':"IF",
       'First Baseman':"1B", 
       'Third Baseman':"3B",
             'Catcher':"C",
      'Second Baseman':"2B",
           'Shortstop':"SS",
        'Pinch Hitter':"PH",
   'Designated Hitter':"DH",
        'Pinch Runner':"PR",
        "P":'Pitcher',
            "OF":'Outfielder',
            "CF":'Centerfielder',
            "LF":'Leftfielder',
            "RF":'Rightfielder',
            "IF":'Infielder',
            "1B":'First Baseman',
            "3B":'Third Baseman',
             "C":'Catcher',
            "2B":'Second Baseman',
            "SS":'Shortstop',
            "PH":'Pinch Hitter',
            "DH":'Designated Hitter',
            "PR":'Pinch Runner'}

players_type= {
    1:"Pitcher",
    2:"Batter"
}

countries = {'af': "Afganistán",
     'as': "Samoa Americana",
     'at': "Austria",
     'au': "Australia",
     'aw': "Aruba",
     'be': "Bélgica",
     'br': "Brasil",
     'bs': "Bután",
     'bz': "Belice",
     'ca': "Canadá",
     'ch': "Suiza",
     'cn': "China",
     'co': "Colombia",
     'cu': "Cuba",
     'cw': "Curaçao",
     'cz': "República Checa",
     'de': "Alemania",
     'desconocido': "Desconocido",
     'dk': "Dinamarca",
     'do': "República Dominicana",
     'es': "España",
     'fi': "Finlandia",
     'fr': "Francia",
     'gb': "Reino Unido",
     'gr': "Grecia",
     'gu': "Guam",
     'hk': "Hong Kong",
     'hn': "Honduras",
     'id': "Indonesia",
     'ie': "Irlanda",
     'it': "Italia",
     'jm': "Jamaica",
     'jp': "Japón",
     'kr': "Corea del Sur",
     'lt': "Lituania",
     'lv': "Letonia",
     'mx': "México",
     'ni': "Nicaragua",
     'nl': "Países Bajos",
     'no': "Noruega",
     'pa': "Panamá",
     'pe': "Perú",
     'ph': "Filipinas",
     'pl': "Polonia",
     'pr': "Puerto Rico",
     'pt': "Portugal",
     'ru': "Rusia",
     'sa': "Arabia Saudí",
     'se': "Suecia",
     'sg': "Singapur",
     'sk': "Eslovaquia",
     'tw': "Taiwán",
     'ua': "Ucrania",
     'us': "Estados Unidos",
     've': "Venezuela",
     'vi': "Islas Vírgenes Americanas",
     'vn': "Vietnam",
     'za': "Sudáfrica"}

leagues_mayors =  {'AL','NL','AA','UA', 'PL','FL','NA'}

negro_leagues = {'ANL','ECL','EWL','NAL','NNL','NN2', 'NSL'}

headers_bio = ['Id', 'Name', 'Active','First year','Last year','Url','Country','Bat hand','Throw hand','Full Name','HoF','HoF type','HoF year','HoF comittee','Player type','retirement_age','total_seasons','career_teams','career_leagues','first_position','second_position','play_in_mayors','play_in_negro_league','two_way_player','debut_decade','retirament_decade']
headers_bat = ['2B_bt','3B_bt','AB_bt','BA_bt','BB_bt','CS_bt','G_bt','HR_bt','H_bt','IBB_bt','OBP_bt','OPS+_bt','OPS_bt','PA_bt','RAA_bt','RAR_bt','RBI_bt','R_bt','Rbaser_bt','Rbat_bt','Rdp_bt','Rfield_bt','Rpos_bt','Rrep_bt','SB_bt','SF_bt','SH_bt','SLG_bt','SO_bt','TB_bt','WAA_bt','WAR_bt','dWAR_bt','oRAR_bt','oWAR_bt','A_fd','CG_fd','CS%_fd','CS_fd','Ch_fd','DP_fd','E_fd','Fld%_fd','GS_fd','G_fd','Inn_fd','PB_fd','PO_fd','RF/9_fd','RF/G_fd','SB_fd','WP_fd']
headers_pit = ['W_pt','L_pt','W-L%_pt','ERA_pt','G_pt','GS_pt','GF_pt','CG_pt','SHO_pt','SV_pt','IP_pt','H_pt','R_pt','ER_pt','HR_pt','BB_pt','IBB_pt','SO_pt','HBP_pt','BK_pt','WP_pt','BF_pt','ERA+_pt','FIP_pt','WHIP_pt','H9_pt','HR9_pt','BB9_pt','SO9_pt','SO/W_pt','RAA_pt','WAA_pt','WAR_pt','RAR_pt']

bat_basic_stats = ['2B_bt','3B_bt','AB_bt','BB_bt','CS_bt','G_bt','HR_bt','H_bt','IBB_bt','PA_bt','RBI_bt','R_bt','SB_bt','HBP_bt','SF_bt','SH_bt','SO_bt']
bat_calc_stats = ['BA_bt', 'OBP_bt','OPS_bt','SLG_bt','TB_bt']
bat_adv_stats = ['OPS+_bt', 'RAA_bt','RAR_bt','Rbaser_bt','Rbat_bt','Rdp_bt','Rfield_bt','Rpos_bt','Rrep_bt', 'WAA_bt','WAR_bt','dWAR_bt','oRAR_bt','oWAR_bt']

field_basic_stats = ['A_fd','CG_fd','CS_fd','DP_fd','E_fd','GS_fd','G_fd','Inn_fd','PB_fd','PO_fd','SB_fd','WP_fd']
field_calc_stats = ['Ch_fd','Fld%_fd']

pit_basic_stats = ['W_pt','L_pt','G_pt','GS_pt','GF_pt','CG_pt','SHO_pt','SV_pt','IP_pt','H_pt','R_pt','ER_pt','HR_pt','BB_pt','IBB_pt','SO_pt','HBP_pt','BK_pt','WP_pt','BF_pt']
pit_calc_stats = ['W-L%_pt','ERA_pt','FIP_pt','WHIP_pt','H9_pt','HR9_pt','BB9_pt','SO9_pt','SO/W_pt']
pit_adv_stats = ['ERA+_pt','RAA_pt','WAA_pt','WAR_pt','RAR_pt']

def get_position_by_reverse_key(pos_name_or_key:str)->str:
    return positions[pos_name_or_key]

def get_player_type_by_key(key:int)->str:
    return players_type[key]

def get_decade(year:float)->int:
    return year-(year%10)

def get_country_by_key(key:str)->str:
    return countries[key]

steroid_reports_players = {
    "Barry Lamar Bonds":"https://www.baseball-reference.com/players/b/bondsba01.shtml",
    "Marvin Larry Benard":"https://www.baseball-reference.com/players/b/benarma01.shtml",
    "Robert M. Estalella":"https://www.baseball-reference.com/players/e/estalbo02.shtml",
    "Jason Gilbert Giambi":"https://www.baseball-reference.com/players/g/giambja01.shtml",
    "Jeremy Dean Giambi":"https://www.baseball-reference.com/players/g/giambje01.shtml",
    "Armando Rios":"https://www.baseball-reference.com/players/r/riosar01.shtml",
    "Benito Santiago":"https://www.baseball-reference.com/players/s/santibe01.shtml",
    "Gary Antonian Sheffield":"https://www.baseball-reference.com/players/s/sheffga01.shtml",
    "Randy Lee Velarde":"https://www.baseball-reference.com/players/v/velarra01.shtml",
    "John Chad Allen":"https://www.baseball-reference.com/players/a/allench01.shtml",
    "Michael John Bell":"https://www.baseball-reference.com/players/b/bellmi02.shtml",
    "Gary David Bennett":"https://www.baseball-reference.com/players/b/bennega01.shtml",
    "Larry Robert Bigbie":"https://www.baseball-reference.com/players/b/bigbila01.shtml",
    "James Kevin Brown":"https://www.baseball-reference.com/players/b/brownke01.shtml",
    "Mark Steven Carreon":"https://www.baseball-reference.com/players/c/carrema01.shtml",
    "Jason Samuel Christiansen":"https://www.baseball-reference.com/players/c/chrisja01.shtml",
    "Howard Roddy Clark":"https://www.baseball-reference.com/players/c/clarkho02.shtml",
    "William Roger Clemens":"https://www.baseball-reference.com/players/c/clemero02.shtml",
    "John Joseph Cust":"https://www.baseball-reference.com/players/c/custja01.shtml",
    "Brendan Kevin Donnelly":"https://www.baseball-reference.com/players/d/donnebr01.shtml",
    "Chris Barton Donnels":"https://www.baseball-reference.com/players/d/donnech01.shtml",
    "Leonard Kyle Dykstra":"https://www.baseball-reference.com/players/d/dykstle01.shtml",
    "Matthew Neil Franco":"https://www.baseball-reference.com/players/f/francma01.shtml",
    "Ryan Ray Franklin":"https://www.baseball-reference.com/players/f/frankry01.shtml",
    "Eric Serge Gagne":"https://www.baseball-reference.com/players/g/gagneer01.shtml",
    "Jason Alan Grimsley":"https://www.baseball-reference.com/players/g/grimsja01.shtml",
    "Jerry Wayne Hairston":"https://www.baseball-reference.com/players/h/hairsje02.shtml",
    "Matthew Tyler Herges":"https://www.baseball-reference.com/players/h/hergema01.shtml",
    "Philip Farrell Hiatt":"https://www.baseball-reference.com/players/h/hiattph01.shtml",
    "Glenallen Hill":"https://www.baseball-reference.com/players/h/hillgl01.shtml",
    "Todd Randolph Hundley":"https://www.baseball-reference.com/players/h/hundlto01.shtml",
    "David Christopher Justice":"https://www.baseball-reference.com/players/j/justida01.shtml",
    "Edward Charles Knoblauch":"https://www.baseball-reference.com/players/k/knoblch01.shtml",
    "Timothy John Laker":"https://www.baseball-reference.com/players/l/lakerti01.shtml",
    "Michael Thomas Lansing":"https://www.baseball-reference.com/players/l/lansimi01.shtml",
    "Paul Anthony Lo Duca":"https://www.baseball-reference.com/players/l/loducpa01.shtml",
    "Exavier Prente Logan":"https://www.baseball-reference.com/players/l/loganno01.shtml",
    "Josias Manzanillo":"https://www.baseball-reference.com/players/m/manzajo01.shtml",
    "Cody Dean McKay":"https://www.baseball-reference.com/players/m/mckayco01.shtml",
    "Kent Franklin Mercker":"https://www.baseball-reference.com/players/m/merckke01.shtml",
    "John Barton Miadich":"https://www.baseball-reference.com/players/m/miadiba01.shtml",
    "William Harold Morris":"https://www.baseball-reference.com/players/m/morriha02.shtml",
    "Dennis Edward Neagle":"https://www.baseball-reference.com/players/n/neaglde01.shtml",
    "James Vo Parque":"https://www.baseball-reference.com/players/p/parquji01.shtml",
    "Andrew Eugene Pettitte":"https://www.baseball-reference.com/players/p/pettian01.shtml",
    "Adam David Piatt":"https://www.baseball-reference.com/players/p/piattad01.shtml",
    "Todd Alan Pratt":"https://www.baseball-reference.com/players/p/prattto02.shtml",
    "Stephen LeCharles Randolph":"https://www.baseball-reference.com/players/r/randost01.shtml",
    "Adam David Riggs":"https://www.baseball-reference.com/players/r/riggsad01.shtml",
    "Brian Michael Roberts":"https://www.baseball-reference.com/players/r/roberbr01.shtml",
    "Frank-Paul Santangelo":"https://www.baseball-reference.com/players/s/santaf.01.shtml",
    "David Vincent Segui":"https://www.baseball-reference.com/players/s/seguida01.shtml",
    "William Michael Stanton":"https://www.baseball-reference.com/players/s/stantmi02.shtml",
    "Miguel Odalis Tejada":"https://www.baseball-reference.com/players/t/tejadmi01.shtml",
    "Maurice Samuel Vaughn":"https://www.baseball-reference.com/players/v/vaughmo01.shtml",
    "Ronald Thomas Villone":"https://www.baseball-reference.com/players/v/villoro01.shtml",
    "Fernando Vina":"https://www.baseball-reference.com/players/v/vinafe01.shtml",
    "Rondell Bernard White":"https://www.baseball-reference.com/players/w/whitero02.shtml",
    "Jeffrey F. Williams":"https://www.baseball-reference.com/players/w/willije02.shtml",
    "Todd Michael Williams":"https://www.baseball-reference.com/players/w/willito02.shtml",
    "Kevin Stacey Young":"https://www.baseball-reference.com/players/y/youngke01.shtml",
    "Gregory Owen Zaun":"https://www.baseball-reference.com/players/z/zaungr01.shtml",
    "Richard Alexander Ankiel":"https://www.baseball-reference.com/players/a/ankieri01.shtml",
    "David Michael Bell":"https://www.baseball-reference.com/players/b/bellda01.shtml",
    "Paul Gregory Byrd":"https://www.baseball-reference.com/players/b/byrdpa01.shtml",
    "Jose Canseco":"https://www.baseball-reference.com/players/c/cansejo01.shtml",
    "Jay Jonathan Gibbons":"https://www.baseball-reference.com/players/g/gibboja01.shtml",
    "Troy Edward Glaus":"https://www.baseball-reference.com/players/g/glaustr01.shtml",
    "Jason Alan Grimsley":"https://www.baseball-reference.com/players/g/grimsja01.shtml",
    "Jose Manuel Guillen":"https://www.baseball-reference.com/players/g/guilljo01.shtml",
    "Jerry Wayne Hairston":"https://www.baseball-reference.com/players/h/hairsje02.shtml",
    "Darren Lee Holmes":"https://www.baseball-reference.com/players/h/holmeda01.shtml",
    "Gary Nathaniel Matthews":"https://www.baseball-reference.com/players/m/matthga02.shtml",
    "John Loy Rocker":"https://www.baseball-reference.com/players/r/rockejo01.shtml",
    "Scott David Schoeneweis":"https://www.baseball-reference.com/players/s/schoesc01.shtml",
    "Ismael Valdez":"https://www.baseball-reference.com/players/v/valdeis01.shtml",
    "Matthew Derrick Williams":"https://www.baseball-reference.com/players/w/willima04.shtml",
    "Steven Larry Woodard":"https://www.baseball-reference.com/players/w/woodast01.shtml",
    "Daniel Donovan Naulty":"https://www.baseball-reference.com/players/n/naultda01.shtml",
    "Wallace Keith Joyner":"https://www.baseball-reference.com/players/j/joynewa01.shtml",
    "Manuel de Jesus Alexander":"https://www.baseball-reference.com/players/a/alexama02.shtml",
    "Ricardo Ricky Bones":"https://www.baseball-reference.com/players/b/bonesri01.shtml",
    "Alexander Alberto Cabrera":"https://www.baseball-reference.com/players/c/cabreal02.shtml",
    "Paxton Keith Crawford":"https://www.baseball-reference.com/players/c/crawfpa02.shtml",
    "Juan Alberto Gonzalez":"https://www.baseball-reference.com/players/g/gonzaju03.shtml",
    "Michael Galen Judd":"https://www.baseball-reference.com/players/j/juddmi01.shtml",
    "Ricky L. Stone":"https://www.baseball-reference.com/players/s/stoneri01.shtml",
    "Alexander Enmanuel Rodriguez":"https://www.baseball-reference.com/players/r/rodrial01.shtml",
    "Mark David McGwire":"https://www.baseball-reference.com/players/m/mcgwima01.shtml",
    "Manuel Aristides Ramirez":"https://www.baseball-reference.com/players/r/ramirma02.shtml",
    "Edinson Volquez":"https://www.baseball-reference.com/players/v/volqued01.shtml",
    "Jenrry Manuel Mejia":"https://www.baseball-reference.com/players/m/mejiaje01.shtml",
    "Michael Francisco Pineda":"https://www.baseball-reference.com/players/p/pinedmi01.shtml",
    "Robinson Jose Canó":"https://www.baseball-reference.com/players/c/canoro01.shtml"
}


hof_players = ['Henry_Aaron_2',
 'Luis_Aparicio_489',
 'Cap_Anson_479',
 'Richie_Ashburn_600',
 'Earl_Averill_672',
 'Roberto_Alomar_301',
 'Luke_Appling_498',
 'Pete_Alexander_208',
 'Johnny_Bench_1364',
 'Lou_Boudreau_1975',
 'Lou_Brock_2306',
 'Roger_Bresnahan_2213',
 'Dan_Brouthers_2351',
 'Dave_Bancroft_860',
 'Wade_Boggs_1819',
 'Willard_Brown_2477',
 'Jeff_Bagwell_741',
 'Home_Run_Baker_798',
 'Mordecai_Brown_2449',
 'Yogi_Berra_1476',
 'Charles_Bender_1366',
 'Cool_Papa_Bell_1305',
 'Craig_Biggio_1572',
 'Ernie_Banks_874',
 'Jesse_Burkett_2682',
 'Harold_Baines_771',
 'Jake_Beckley_1246',
 'Jim_Bottomley_1968',
 'Ray_Brown_2459',
 'Jim_Bunning_2620',
 'George_Brett_2218',
 'Bert_Blyleven_1782',
 'Max_Carey_3078',
 'Stan_Coveleski_4237',
 'Roy_Campanella_2963',
 'Kiki_Cuyler_4586',
 'Jack_Chesbro_3497',
 'Roberto_Clemente_3736',
 'Sam_Crawford_4332',
 'Frank_Chance_3419',
 'Fred_Clarke_3681',
 'Earle_Combs_3943',
 'Eddie_Collins_3902',
 'Gary_Carter_3197',
 'John_Clarkson_3699',
 'Rod_Carew_3076',
 'Roger_Connor_4008',
 'Steve_Carlton_3108',
 'Jimmy_Collins_3907',
 'Ty_Cobb_3789',
 'Orlando_Cepeda_3371',
 'Oscar_Charleston_3460',
 'Mickey_Cochrane_3796',
 'Joe_Cronin_4403',
 'Andy_Cooper_4086',
 'Bill_Dickey_5198',
 'Martín_Dihigo_5230',
 'Joe_DiMaggio_5250',
 'Leon_Day_4876',
 'Bobby_Doerr_5317',
 'George_Davis_4789',
 'Ed_Delahanty_5009',
 'Dizzy_Dean_4935',
 'Don_Drysdale_5533',
 'Andre_Dawson_4865',
 'Ray_Dandridge_4654',
 'Larry_Doby_5308',
 'Hugh_Duffy_5570',
 'Dennis_Eckersley_5763',
 'Buck_Ewing_6107',
 'Johnny_Evers_6102',
 'Jimmie_Foxx_6708',
 'Elmer_Flick_6521',
 'Nellie_Fox_6704',
 'Carlton_Fisk_6447',
 'Bill_Foster_6654',
 'Frankie_Frisch_6837',
 'Rick_Ferrell_6300',
 'Rollie_Fingers_6385',
 'Bob_Feller_6253',
 'Whitey_Ford_6621',
 'Red_Faber_6121',
 'Lou_Gehrig_7216',
 'Bob_Gibson_7309',
 'Josh_Gibson_7316',
 'Vladimir_Guerrero_8046',
 'Hank_Greenberg_7863',
 'Charlie_Gehringer_7218',
 'Tom_Glavine_7466',
 'Pud_Galvin_6988',
 'Rich_Gossage_7702',
 'Goose_Goslin_7699',
 'Joe_Gordon_7669',
 'Ken_Griffey_Jr._7920',
 'Tony_Gwynn_8131',
 'Lefty_Gomez_7566',
 'Lefty_Grove_8005',
 'Burleigh_Grimes_7959',
 'Harry_Heilmann_8780',
 'Harry_Hooper_9419',
 'Gabby_Hartnett_8580',
 'Trevor_Hoffman_9285',
 'Gil_Hodges_9252',
 'Chick_Hafey_8166',
 'Pete_Hill_9161',
 'Roy_Halladay_8255',
 'Jesse_Haines_8191',
 'Rogers_Hornsby_9458',
 'Rickey_Henderson_8852',
 'Waite_Hoyt_9578',
 'Carl_Hubbell_9592',
 'Catfish_Hunter_9719',
 'Billy_Hamilton_8281',
 'Billy_Herman_8934',
 'Monte_Irvin_9823',
 'Addie_Joss_10475',
 'Derek_Jeter_10074',
 'Reggie_Jackson_9899',
 'Fergie_Jenkins_10039',
 'Randy_Johnson_10245',
 'Hughie_Jennings_10056',
 'Chipper_Jones_10334',
 'Judy_Johnson_10210',
 'Travis_Jackson_9913',
 'Walter_Johnson_10277',
 'Al_Kaline_10543',
 'Harmon_Killebrew_10852',
 'Joe_Kelley_10676',
 'George_Kell_10657',
 'Ralph_Kiner_10887',
 'Chuck_Klein_10986',
 'Jim_Kaat_10521',
 'Tim_Keefe_10628',
 'Willie_Keeler_10631',
 'King_Kelly_10709',
 'High_Pockets_Kelly_10700',
 'Sandy_Koufax_11164',
 'Barry_Larkin_11467',
 'Ernie_Lombardi_12036',
 'Nap_Lajoie_11345',
 'Ted_Lyons_12310',
 'Bob_Lemon_11700',
 'Tony_Lazzeri_11572',
 'Buck_Leonard_11726',
 'Freddie_Lindstrom_11894',
 'John_Henry_Lloyd_11965',
 'Heinie_Manush_12601',
 'Biz_Mackey_12367',
 'José_Mendéz_13624',
 'Stan_Musial_14594',
 'Rabbit_Maranville_12614',
 'Johnny_Mize_14021',
 'Bill_Mazeroski_13012',
 'Willie_Mays_13003',
 'Willie_McCovey_13162',
 'Paul_Molitor_14059',
 'Pedro_Martinez_12801',
 'Greg_Maddux_12396',
 'Bid_McPhee_13495',
 'Jack_Morris_14312',
 'Eddie_Mathews_12873',
 'Joe_McGinnity_13302',
 'Joe_Medwick_13558',
 'Joe_Morgan_14267',
 'Christy_Mathewson_12878',
 'Juan_Marichal_12628',
 'Rube_Marquard_12656',
 'Tommy_McCarthy_13097',
 'Eddie_Murray_14569',
 'Edgar_Martinez_12779',
 'Mike_Mussina_14601',
 'Minnie_Minoso_13960',
 'Mickey_Mantle_12592',
 'Phil_Niekro_14869',
 'Hal_Newhouser_14803',
 'Kid_Nichols_14841',
 'Tony_Oliva_15203',
 'Rourke_15115',
 'Mel_Ott_15361',
 'David_Ortiz_15299',
 'Mike_Piazza_16075',
 'Satchel_Paige_15470',
 'Tony_Perez_15886',
 'Herb_Pennock_15814',
 'Gaylord_Perry_15922',
 'Eddie_Plank_16194',
 'Kirby_Puckett_16458',
 'Jim_Palmer_15493',
 'Robin_Roberts_17240',
 'Ivan_Rodriguez_17380',
 'Brooks_Robinson_17278',
 'Bullet_Rogan_17427',
 'Cal_Ripken_Jr._17143',
 'Tim_Raines_16601',
 'Frank_Robinson_17293',
 'Phil_Rizzuto_17198',
 'Mariano_Rivera_17181',
 'Sam_Rice_17016',
 'Eppa_Rixey_17194',
 'Red_Ruffing_17704',
 'Jackie_Robinson_17302',
 'Pee_Wee_Reese_16829',
 'Babe_Ruth_17764',
 'Edd_Roush_17637',
 'Amos_Rusie_17732',
 'Jim_Rice_17013',
 'Nolan_Ryan_17793',
 'Old_Hoss_Radbourn_16571',
 'Ron_Santo_17999',
 'Ted_Simmons_18754',
 'Ozzie_Smith_19061',
 'Red_Schoendienst_18210',
 'Tris_Speaker_19279',
 'Turkey_Stearnes_19473',
 'Al_Simmons_18743',
 'Don_Sutton_19894',
 'Tom_Seaver_18362',
 'Warren_Spahn_19263',
 'Joe_Sewell_18455',
 'Ray_Schalk_18109',
 'Mule_Suttles_19893',
 'Duke_Snider_19142',
 'Enos_Slaughter_18860',
 'Lee_Smith_19041',
 'Ryne_Sandberg_17936',
 'Mike_Schmidt_18193',
 'Willie_Stargell_19446',
 'Louis_Santop_18001',
 'George_Sisler_18809',
 'John_Smoltz_19118',
 'Hilton_Smith_19012',
 'Bruce_Sutter_19891',
 'Alan_Trammell_20584',
 'Sam_Thompson_20363',
 'Bill_Terry_20199',
 'Frank_Thomas_20274',
 'Pie_Traynor_20597',
 'Jim_Thome_20314',
 'Joe_Tinker_20442',
 'Cristóbal_Torriente_20550',
 'Ben_Taylor_20084',
 'Arky_Vaughan_20947',
 'Dazzy_Vance_20906',
 'Larry_Walker_21220',
 'Ed_Walsh_21288',
 'John_Ward_21344',
 'Rube_Waddell_21126',
 'Jud_Wilson_22106',
 'Lloyd_Waner_21321',
 'Dave_Winfield_22157',
 'Deacon_White_21709',
 'Early_Wynn_22427',
 'Paul_Waner_21322',
 'Honus_Wagner_21152',
 'Hoyt_Wilhelm_21837',
 'Bobby_Wallace_21256',
 'Mickey_Welch_21557',
 'Willie_Wells_21589',
 'Ted_Williams_21996',
 'Hack_Wilson_22089',
 'Joe_Williams_21940',
 'Vic_Willis_22028',
 'Zack_Wheat_21663',
 'Billy_Williams_21882',
 'Robin_Yount_22574',
 'Ross_Youngs_22570',
 'Carl_Yastrzemski_22459',
 'Cy_Young_22523']
