steroid_repsteroid_reports_players ={
    "David Vincent Segui":"https://www.baseball-reference.com/players/s/seguida01.shtml",
    "William Michael Stanton":"https://www.baseball-reference.com/players/s/stantmi02.shtml",
    "Miguel Odalis Tejada":"https://www.baseball-reference.com/players/t/tejadmi01.shtml",
    "Maurice Samuel Vaughn":"https://www.baseball-reference.com/players/v/vaughmo01.shtml",
    "Ronald Thomas Villone":"https://www.baseball-reference.com/players/v/villoro01.shtml",
    "Fernando Vina":"https://www.baseball-reference.com/players/v/vinafe01.shtml",
    "Rondell Bernard White":"https://www.baseball-reference.com/players/w/whitero02.shtml",
    "Jeffrey F. Williams":"https://www.baseball-reference.com/players/w/willije02.shtml",
    "Todd Michael Williams":"https://www.baseball-reference.com/players/w/willito02.shtml",
    "Kevin Stacey Young":"https://www.baseball-reference.com/players/y/youngke01.shtml",
    "Gregory Owen Zaun":"https://www.baseball-reference.com/players/z/zaungr01.shtml",
    "Richard Alexander Ankiel":"https://www.baseball-reference.com/players/a/ankieri01.shtml",
    "David Michael Bell":"https://www.baseball-reference.com/players/b/bellda01.shtml",
    "Paul Gregory Byrd":"https://www.baseball-reference.com/players/b/byrdpa01.shtml",
    "Jose Canseco":"https://www.baseball-reference.com/players/c/cansejo01.shtml",
    "Jay Jonathan Gibbons":"https://www.baseball-reference.com/players/g/gibboja01.shtml",
    "Troy Edward Glaus":"https://www.baseball-reference.com/players/g/glaustr01.shtml",
    "Jason Alan Grimsley":"https://www.baseball-reference.com/players/g/grimsja01.shtml",
    "Jose Manuel Guillen":"https://www.baseball-reference.com/players/g/guilljo01.shtml",
    "Jerry Wayne Hairston":"https://www.baseball-reference.com/players/h/hairsje02.shtml",
    "Darren Lee Holmes":"https://www.baseball-reference.com/players/h/holmeda01.shtml",
    "Gary Nathaniel Matthews":"https://www.baseball-reference.com/players/m/matthga02.shtml",
    "John Loy Rocker":"https://www.baseball-reference.com/players/r/rockejo01.shtml",
    "Scott David Schoeneweis":"https://www.baseball-reference.com/players/s/schoesc01.shtml",
    "Ismael Valdez":"https://www.baseball-reference.com/players/v/valdeis01.shtml",
    "Matthew Derrick Williams":"https://www.baseball-reference.com/players/w/willima04.shtml",
    "Steven Larry Woodard":"https://www.baseball-reference.com/players/w/woodast01.shtml",
    "Daniel Donovan Naulty":"https://www.baseball-reference.com/players/n/naultda01.shtml",
    "Wallace Keith Joyner":"https://www.baseball-reference.com/players/j/joynewa01.shtml",
    "Manuel de Jesus Alexander":"https://www.baseball-reference.com/players/a/alexama02.shtml",
    "Ricardo Ricky Bones":"https://www.baseball-reference.com/players/b/bonesri01.shtml",
    "Alexander Alberto Cabrera":"https://www.baseball-reference.com/players/c/cabreal02.shtml",
    "Paxton Keith Crawford":"https://www.baseball-reference.com/players/c/crawfpa02.shtml",
    "Juan Alberto Gonzalez":"https://www.baseball-reference.com/players/g/gonzaju03.shtml",
    "Michael Galen Judd":"https://www.baseball-reference.com/players/j/juddmi01.shtml",
    "Ricky L. Stone":"https://www.baseball-reference.com/players/s/stoneri01.shtml"
 }